### ISSUE TITLE
Crash after logging in...

### ISSUE THREAD

**Issue by jonaaa20** [coman3/Google.Music.Downloader#1]
When i put my google credentials, it crashes "Google Music Downloader" stopped working...

**Comment by coman3** [comment]
Really!? Do you have 2 Factor Authentication enabled?

**Comment by jonaaa20** [comment]
No, is disabled...

**Comment by coman3** [comment]
Okay i had a look into it, and it seems that it crashes while processing the data received from google...
Further looks into this seem to suggest that the file: `Newtonsoft.Json.dll` is not found within the install folder, or next to the executable... Do you mind checking if this file is located next to the executable  `Google.Music.Downloader.exe`?

**Comment by jonaaa20** [comment]
Here are the contents of the folder:
![screenshot_1](https://cloud.githubusercontent.com/assets/19306370/19019303/81f336e4-8859-11e6-9462-56c3e13ba8ac.png)

**Comment by coman3** [comment]
Humm okay, maybe its something to do with the language set on your computer..... As i released this set to English 😕 (It works fine on my computer as shown in the video....)... Let me have a look into it 😄

**Comment by jonaaa20** [comment]
Language? oh, my PC is set to Portuguese, maybe this is the problem...

umm, just a little question, i need any "Premium" account on Play Music to use the Downloader?

**Comment by coman3** [comment]
Yes you defiantly do need a premium account, this is for accessing All Access Tracks (meaning the songs provided from the premium account service)

**Comment by lzmichael** [comment]
same here, after login the app crashes...how i can fix it ?

windows 10 64bit

**Comment by lzmichael** [comment]
I have found the "bug" now. you need to create a PLAYLIST in your google-music account then the tool works fine :)

if you dont have created a playlist the app crashes after login.
